export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

export const FETCH_USER_VIDEOS_REQUEST = 'FETCH_USER_VIDEOS_REQUEST';
export const FETCH_USER_VIDEOS_SUCCESS = 'FETCH_USER_VIDEOS_SUCCESS';
export const FETCH_USER_VIDEOS_FAILURE = 'FETCH_USER_VIDEOS_FAILURE';

export const FETCH_PUBLIC_VIDEOS_SUCCESS = 'FETCH_PUBLIC_VIDEOS_SUCCESS';
export const FETCH_PUBLIC_VIDEOS_FAILURE = 'FETCH_PUBLIC_VIDEOS_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const SET_VIDEO_PRIVACY_SUCCESS = 'SET_VIDEO_PRIVACY_SUCCESS';

export const LIKE_VIDEO_SUCCESS = 'LIKE_VIDEO_SUCCESS';
export const LIKE_VIDEO_FAILURE = 'LIKE_VIDEO_FAILURE';